---
- name: Minecraftオンデマンドサーバーをデプロイする
  hosts: all
  become: true
  vars:
    base_dir: /opt/minecraft-on-demand
    venv_dir: "{{ base_dir }}/venv"
    systemd_dir: /etc/systemd/system

  tasks:
    - name: apt パッケージを更新
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 依存パッケージをインストール（apt-transport-https等）
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Docker用GPGキーを配置
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Dockerリポジトリを追加
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: DockerとCompose v2をインストール
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: docker グループに現在のユーザーを追加
      user:
        name: "{{ ansible_user | default(ansible_user_id) }}"
        groups: docker
        append: yes
      when: ansible_user_id != 'root'

    - name: Dockerデーモンを起動・有効化
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: ベースディレクトリを作成する
      file:
        path: "{{ base_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: プロジェクトファイルを配置する（{{ base_dir }}）
      copy:
        src: "files/{{ item }}"
        dest: "{{ base_dir }}/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - main.py
        - compose.yaml
        - requirements.txt

    - name: systemdユニットファイルを配置する（{{ systemd_dir }}）
      copy:
        src: "files/{{ item }}"
        dest: "{{ systemd_dir }}/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - minecraft-on-demand.socket
        - minecraft-on-demand@.service
      notify:
        - systemdをリロードする

    - name: venv作成に必要なパッケージをインストール
      apt:
        name: python3.12-venv
        state: present

    - name: Python仮想環境を作成する（存在しない場合のみ）
      command: python3 -m venv "{{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Python依存パッケージをインストールする
      pip:
        requirements: "{{ base_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python3

    - name: socketサービスを有効化し起動する
      systemd:
        name: minecraft-on-demand.socket
        enabled: true
        state: started

  handlers:
    - name: systemdをリロードする
      command: systemctl daemon-reload
